#ifndef __MAP_H

//this file is included in map.c only
//it is not visible for other source files

#include "str.h"
static tTable tabMnu; //menu tree
static tContainer cntMnu;
static byte mnuCache[lenMnu*DIM(mnuBeg,mnuEnd)];

static tTable tabMsg; //screen messages
static tContainer cntMsg;
static byte msgCache[dspW*DIM(msgBeg,msgEnd)];

static tTable tabMon; //month names
static tContainer cntMon;
static byte monCache[lenMon*DIM(monBeg,monEnd)];

static tRecord recTot; //totals record
static tContainer cntTot;
static word totLen[DIM(totBeg,totEnd)]= {
    lenTotAmt,  //totAppDbAmt
    sizeof(word),  //totAppDbCnt
    lenTotAmt,  //totAppCrAmt
    sizeof(word),  //totAppCrCnt
    lenTotAmt,  //totAppTpAmt
    sizeof(word),  //totAppTpCnt
    lenTotAmt,  //totAppSaleAmt
    sizeof(word),  //totAppSaleCnt
    lenTotAmt,  //totAppRefundAmt
    sizeof(word),  //totAppRefundCnt
    lenTotAmt,  //totAppOfflineAmt
    sizeof(word),  //totAppOfflineCnt
    lenTotAmt,  //totAppManualAmt
    sizeof(word),  //totAppManualCnt
    lenTotAmt,  //totAppVoidAmt
    sizeof(word),  //totAppVoidCnt
    lenDatTim,  //totDatTim
    lenBatNum,  //totBatNum
    lenTotAmt,  //totAppTopUpAmt
    sizeof(word),  //totAppTopUpCnt
    lenTotAmt,  //totAppUpdateAmt
    sizeof(word),  //totAppUpdateCnt
    lenTotAmt,  //totAppTelkomAmt
    sizeof(word),  //totAppTelkomCnt
    lenTotAmt,  //totAppSatelindoAmt
    sizeof(word),  //totAppSatelindoCnt
    lenTotAmt,  //totAppTelkomselAmt
    sizeof(word),  //totAppTelkomselCnt
    lenTotAmt,  //totAppExcelcomAmt
    sizeof(word),  //totAppExcelcomCnt
    lenTotAmt,  //totAppEsiaAmt
    sizeof(word),  //totAppEsiaCnt
    lenTotAmt,  //totAppPLNAmt
    sizeof(word),  //totAppPLNCnt
    lenTotAmt,  //totAppFirstMEdiaAmt
    sizeof(word),  //totAppFirstMEdiaCnt
    lenTotAmt,  //totAppIndovisionAmt
    sizeof(word),  //totAppIndovisionCnt
    lenTotAmt,  //totAppOtoMultiAmt
    sizeof(word),  //totAppOtoMultiCnt
    lenTotAmt,  //totAppMAtmAmt
    lenTotAmt,  //totAppAmountMINIATM
    sizeof(word),  //totAppMAtmCnt
    lenTotAmt,  //totAppPurchaseAmtGP
    sizeof(word),  //totAppPurchaseCntGP
    lenTotAmt,  //totAppTunaiAmt
    sizeof(word),  //totAppTunaiCnt
    lenTotAmt,  //totAppTransferAmt
    sizeof(word),  //totAppTransferCnt
    lenTotAmt,  //totAppCCAmt
    sizeof(word),  //totAppCCCnt
    lenTotAmt,  //totAppOnUsAmt
    sizeof(word),  //totAppOnUsCnt
    lenTotAmt,  //totAppOffUsAmt
    sizeof(word),  //totAppOffUsCnt
    lenTotAmt,  //totAppDBOnUsAmt
    sizeof(word),  //totAppDBOnUsCnt
    lenTotAmt,  //totAppMCOnUsAmt
    sizeof(word),  //totAppMCOnUsCnt
    lenTotAmt,  //totAppMCOffUsAmt
    sizeof(word),  //totAppMCOffUsCnt
    lenTotAmt,  //totAppVSOnUsAmt
    sizeof(word),  //totAppVSOnUsCnt
    lenTotAmt,  //totAppVSOffUsAmt
    sizeof(word),  //totAppVSOffUsCnt
    lenTotAmt,  //totAppMCPBAmt
    sizeof(word),  //totAppMCPBCnt
    lenTotAmt,  //totAppVSPBAmt
    sizeof(word),  //totAppVSPBCnt
};
static word totMap[DIM(totBeg,totEnd)];
static char totFmt[DIM(totBeg,totEnd)]= {
    'A',  //totAppDbAmt
    'N',  //totAppDbCnt
    'A',  //totAppCrAmt
    'N',  //totAppCrCnt
    'A',  //totAppTpAmt
    'N',  //totAppTpCnt
    'A',  //totAppSaleAmt
    'N',  //totAppSaleCnt
    'A',  //totAppRefundAmt
    'N',  //totAppRefundCnt
    'A',  //totAppOfflineAmt
    'N',  //totAppOfflineCnt
    'A',  //totAppManualAmt
    'N',  //totAppManualCnt
    'A',  //totAppVoidAmt
    'N',  //totAppVoidCnt
    'A',  //totDatTim
    'A',  //totBatNum
    'A',  //totAppTopUpAmt
    'N',  //totAppTopUpCnt
    'A',  //totAppUpdateAmt
    'N',  //totAppUpdateCnt
    'A',  //totAppTelkomAmt
    'N',  //totAppTelkomCnt
    'A',  //totAppSatelindoAmt
    'N',  //totAppSatelindoCnt
    'A',  //totAppTelkomselAmt
    'N',  //totAppTelkomselCnt
    'A',  //totAppExcelcomAmt
    'N',  //totAppExcelcomCnt
    'A',  //totAppEsiaAmt
    'N',  //totAppEsiaCnt
    'A',  //totAppPLNAmt
    'N',  //totAppPLNCnt
    'A',  //totAppFirstMEdiaAmt
    'N',  //totAppFirstMEdiaCnt
    'A',  //totAppIndovisionAmt
    'N',  //totAppIndovisionCnt
    'A',  //totAppOtoMultiAmt
    'N',  //totAppOtoMultiCnt
    'A',  //totAppMAtmAmt
    'A',  //totAppAmountMINIATM
    'N',  //totAppMAtmCnt
    'A',  //totAppPurchaseAmtGP
    'N',  //totAppPurchaseCntGP
    'A',  //totAppTunaiAmt
    'N',  //totAppTunaiCnt
    'A',  //totAppTransferAmt
    'N',  //totAppTransferCnt
    'A',  //totAppCCAmt
    'N',  //totAppCCCnt
    'A',  //totAppOnUsAmt
    'N',  //totAppOnUsCnt
    'A',  //totAppOffUsAmt
    'N',  //totAppOffUsCnt
    'A',  //totAppDBOnUsAmt
    'N',  //totAppDBOnUsCnt
    'A',  //totAppMCOnUsAmt
    'N',  //totAppMCOnUsCnt
    'A',  //totAppMCOffUsAmt
    'N',  //totAppMCOffUsCnt
    'A',  //totAppVSOnUsAmt
    'N',  //totAppVSOnUsCnt
    'A',  //totAppVSOffUsAmt
    'N',  //totAppVSOffUsCnt
    'A',  //totAppMCPBAmt
    'N',  //totAppMCPBCnt
    'A',  //totAppVSPBAmt
    'N',  //totAppVSPBCnt
};

static tRecord recCdb; //bank code multi record
static tTable tabCdb;
static tContainer cntCdb;
static word cdbLen[DIM(cdbBeg,cdbEnd)]= {
    3,  //cdbBankKode
    15,  //cdbBankName
};
static word cdbMap[DIM(cdbBeg,cdbEnd)];
static char cdbFmt[DIM(cdbBeg,cdbEnd)]= {
    'A',  //cdbBankKode
    'A',  //cdbBankName
};

static tRecord recBin; //Card Range multirecord
static tTable tabBin;
static tContainer cntBin;
static word binLen[DIM(binBeg,binEnd)]= {
    sizeof(byte),  //binID
    lenTotAmt,  //binTotAppDbAmt
    sizeof(word),  //binTotAppDbCnt
    lenTotAmt,  //binTotAppCrAmt
    sizeof(word),  //binTotAppCrCnt
    lenTotAmt,  //binTotAppTpAmt
    sizeof(word),  //binTotAppTpCnt
};
static word binMap[DIM(binBeg,binEnd)];
static char binFmt[DIM(binBeg,binEnd)]= {
    'N',  //binID
    'A',  //binTotAppDbAmt
    'N',  //binTotAppDbCnt
    'A',  //binTotAppCrAmt
    'N',  //binTotAppCrCnt
    'A',  //binTotAppTpAmt
    'N',  //binTotAppTpCnt
};

static tRecord recAcq; //Acquirer Structure
static tTable tabAcq;
static tContainer cntAcq;
static word acqLen[DIM(acqBeg,acqEnd)]= {
    sizeof(byte),  //acqID
    lenName,  //acqName
    lenInvNum,  //acqCurBat
    lenInvNum,  //logAcqCurBat
    lenTotAmt,  //acqTotAppDbAmt
    sizeof(word),  //acqTotAppDbCnt
    lenTotAmt,  //acqTotAppCrAmt
    sizeof(word),  //acqTotAppCrCnt
    lenTotAmt,  //acqTotAppTpAmt
    sizeof(word),  //acqTotAppTpCnt
    lenTotAmt,  //acqTotAppSaleAmt
    sizeof(word),  //acqTotAppSaleCnt
    lenTotAmt,  //acqTotAppRefundAmt
    sizeof(word),  //acqTotAppRefundCnt
    lenTotAmt,  //acqTotAppOfflineAmt
    sizeof(word),  //acqTotAppOfflineCnt
    lenTotAmt,  //acqTotAppManualAmt
    sizeof(word),  //acqTotAppManualCnt
    lenTotAmt,  //acqTotAppVoidAmt
    sizeof(word),  //acqTotAppVoidCnt
    lenTotAmt,  //acqTotAppPrepaidAmt
    sizeof(word),  //acqTotAppPrepaidCnt
    lenTotAmt,  //acqTotAppPrepaidAmtUpdate
    sizeof(word),  //acqTotAppPrepaidCntUpdate
    lenTotAmt,  //logAcqTotAppAmtPrepaid
    sizeof(word),  //logAcqTotAppCntPrepaid
    lenTotAmt,  //logAcqTotAppAmtPrepaidUpdate
    sizeof(word),  //logAcqTotAppCntPrepaidUpdate
    lenTotAmt,  //acqTotAppTelkomAmt
    sizeof(word),  //acqTotAppTelkomCnt
    lenTotAmt,  //acqTotAppSatelindoAmt
    sizeof(word),  //acqTotAppSatelindoCnt
    lenTotAmt,  //acqTotAppTelkomselAmt
    sizeof(word),  //acqTotAppTelkomselCnt
    lenTotAmt,  //acqTotAppExcelcomAmt
    sizeof(word),  //acqTotAppExcelcomCnt
    lenTotAmt,  //acqTotAppEsiaAmt
    sizeof(word),  //acqTotAppEsiaCnt
    lenTotAmt,  //acqTotAppPLNAmt
    sizeof(word),  //acqTotAppPLNCnt
    lenTotAmt,  //acqTotAppFirstMediaAmt
    sizeof(word),  //acqTotAppFirstMediaCnt
    lenTotAmt,  //acqTotAppIndovisionAmt
    sizeof(word),  //acqTotAppIndovisionCnt
    lenTotAmt,  //acqTotAppOtoMultiAmt
    sizeof(word),  //acqTotAppOtoMultiCnt
    lenTotAmt,  //acqTotAppMAtmAmt
    sizeof(word),  //acqTotAppMAtmCnt
    lenTotAmt,  //acqTotAppMINIATMAmt
    lenTotAmt,  //acqTotAppPrepaidAmtGP
    sizeof(word),  //acqTotAppPrepaidCntGP
    lenTotAmt,  //logAcqTotAppAmtPrepaidGP
    sizeof(word),  //logAcqTotAppCntPrepaidGP
    lenTotAmt,  //acqTotAppAmtTunai
    sizeof(word),  //acqTotAppCntTunai
    lenTotAmt,  //acqTotAppAmtTransfer
    sizeof(word),  //acqTotAppCntTransfer
    lenTotAmt,  //acqTotAppAmtCC
    sizeof(word),  //acqTotAppCntCC
    lenTotAmt,  //acqTotAppAmtTransferUSD
    sizeof(word),  //acqTotAppCntTransferUSD
    lenTotAmt,  //acqTotAppAmtTransferSGD
    sizeof(word),  //acqTotAppCntTransferSGD
    lenTotAmt,  //acqTotAppAmtTransferJPN
    sizeof(word),  //acqTotAppCntTransferJPN
    lenTotAmt,  //logAcqTotAppAmtTunai
    sizeof(word),  //logAcqTotAppCntTunai
    lenTotAmt,  //logAcqTotAppAmtTransfer
    sizeof(word),  //logAcqTotAppCntTransfer
    lenTotAmt,  //logAcqTotAppAmtCC
    sizeof(word),  //logAcqTotAppCntCC
    lenTotAmt,  //logAcqTotAppAmtTransferUSD
    sizeof(word),  //logAcqTotAppCntTransferUSD
    lenTotAmt,  //logAcqTotAppAmtTransferSGD
    sizeof(word),  //logAcqTotAppCntTransferSGD
    lenTotAmt,  //logAcqTotAppAmtTransferJPN
    sizeof(word),  //logAcqTotAppCntTransferJPN
    sizeof(word),  //acqTotAppCommCnt
    sizeof(word),  //logAcqTotAppCntComm
    lenTotAmt,  //logacqTotAppTelkomAmt
    sizeof(word),  //logacqTotAppTelkomCnt
    lenTotAmt,  //logacqTotAppSatelindoAmt
    sizeof(word),  //logacqTotAppSatelindoCnt
    lenTotAmt,  //logacqTotAppTelkomselAmt
    sizeof(word),  //logacqTotAppTelkomselCnt
    lenTotAmt,  //logacqTotAppExcelcomAmt
    sizeof(word),  //logacqTotAppExcelcomCnt
    lenTotAmt,  //logacqTotAppEsiaAmt
    sizeof(word),  //logacqTotAppEsiaCnt
    lenTotAmt,  //logacqTotAppPLNAmt
    sizeof(word),  //logacqTotAppPLNCnt
    lenTotAmt,  //logacqTotAppFirstMediaAmt
    sizeof(word),  //logacqTotAppFirstMediaCnt
    lenTotAmt,  //logacqTotAppIndovisionAmt
    sizeof(word),  //logacqTotAppIndovisionCnt
    lenTotAmt,  //logacqTotAppOtoMultiAmt
    sizeof(word),  //logacqTotAppOtoMultiCnt
    lenTotAmt,  //logacqTotAppMAtmAmt
    sizeof(word),  //logacqTotAppMAtmCnt
    lenTotAmt,  //logacqTotAppMINIATMAmt
    lenTotAmt,  //logAcqTotAppDbAmt
    sizeof(word),  //logAcqTotAppDbCnt
    lenTotAmt,  //logAcqTotAppVoidAmt
    sizeof(word),  //logAcqTotAppVoidCnt
    lenTotAmt,  //logAcqTotAppTipAmt
    sizeof(word),  //logAcqTotAppTipCnt
    lenSrv,  //acqPriTxnPhnSrv
    lenSrv,  //acqSecTxnPhnSrv
    lenSrv,  //acqPriStlPhnSrv
    lenSrv,  //acqSecStlPhnSrv
    lenSrv,  //acqPriTxnIPSrv
    lenSrv,  //acqSecTxnIPSrv
    lenSrv,  //acqPriStlIPSrv
    lenSrv,  //acqSecStlIPSrv
    lenMKey,  //acqMasterKey1
    lenMKey,  //acqMasterKey2
    16,  //acqWorkingKey
    16,  //acqPinKey
    sizeof(byte),  //acqPendingSettle
    sizeof(byte),  //acqLogonFlag
    sizeof(byte),  //acqFlagCountTrx
};
static word acqMap[DIM(acqBeg,acqEnd)];
static char acqFmt[DIM(acqBeg,acqEnd)]= {
    'N',  //acqID
    'A',  //acqName
    'A',  //acqCurBat
    'A',  //logAcqCurBat
    'A',  //acqTotAppDbAmt
    'N',  //acqTotAppDbCnt
    'A',  //acqTotAppCrAmt
    'N',  //acqTotAppCrCnt
    'A',  //acqTotAppTpAmt
    'N',  //acqTotAppTpCnt
    'A',  //acqTotAppSaleAmt
    'N',  //acqTotAppSaleCnt
    'A',  //acqTotAppRefundAmt
    'N',  //acqTotAppRefundCnt
    'A',  //acqTotAppOfflineAmt
    'N',  //acqTotAppOfflineCnt
    'A',  //acqTotAppManualAmt
    'N',  //acqTotAppManualCnt
    'A',  //acqTotAppVoidAmt
    'N',  //acqTotAppVoidCnt
    'A',  //acqTotAppPrepaidAmt
    'N',  //acqTotAppPrepaidCnt
    'A',  //acqTotAppPrepaidAmtUpdate
    'N',  //acqTotAppPrepaidCntUpdate
    'A',  //logAcqTotAppAmtPrepaid
    'N',  //logAcqTotAppCntPrepaid
    'A',  //logAcqTotAppAmtPrepaidUpdate
    'N',  //logAcqTotAppCntPrepaidUpdate
    'A',  //acqTotAppTelkomAmt
    'N',  //acqTotAppTelkomCnt
    'A',  //acqTotAppSatelindoAmt
    'N',  //acqTotAppSatelindoCnt
    'A',  //acqTotAppTelkomselAmt
    'N',  //acqTotAppTelkomselCnt
    'A',  //acqTotAppExcelcomAmt
    'N',  //acqTotAppExcelcomCnt
    'A',  //acqTotAppEsiaAmt
    'N',  //acqTotAppEsiaCnt
    'A',  //acqTotAppPLNAmt
    'N',  //acqTotAppPLNCnt
    'A',  //acqTotAppFirstMediaAmt
    'N',  //acqTotAppFirstMediaCnt
    'A',  //acqTotAppIndovisionAmt
    'N',  //acqTotAppIndovisionCnt
    'A',  //acqTotAppOtoMultiAmt
    'N',  //acqTotAppOtoMultiCnt
    'A',  //acqTotAppMAtmAmt
    'N',  //acqTotAppMAtmCnt
    'A',  //acqTotAppMINIATMAmt
    'A',  //acqTotAppPrepaidAmtGP
    'N',  //acqTotAppPrepaidCntGP
    'A',  //logAcqTotAppAmtPrepaidGP
    'N',  //logAcqTotAppCntPrepaidGP
    'A',  //acqTotAppAmtTunai
    'N',  //acqTotAppCntTunai
    'A',  //acqTotAppAmtTransfer
    'N',  //acqTotAppCntTransfer
    'A',  //acqTotAppAmtCC
    'N',  //acqTotAppCntCC
    'A',  //acqTotAppAmtTransferUSD
    'N',  //acqTotAppCntTransferUSD
    'A',  //acqTotAppAmtTransferSGD
    'N',  //acqTotAppCntTransferSGD
    'A',  //acqTotAppAmtTransferJPN
    'N',  //acqTotAppCntTransferJPN
    'A',  //logAcqTotAppAmtTunai
    'N',  //logAcqTotAppCntTunai
    'A',  //logAcqTotAppAmtTransfer
    'N',  //logAcqTotAppCntTransfer
    'A',  //logAcqTotAppAmtCC
    'N',  //logAcqTotAppCntCC
    'A',  //logAcqTotAppAmtTransferUSD
    'N',  //logAcqTotAppCntTransferUSD
    'A',  //logAcqTotAppAmtTransferSGD
    'N',  //logAcqTotAppCntTransferSGD
    'A',  //logAcqTotAppAmtTransferJPN
    'N',  //logAcqTotAppCntTransferJPN
    'N',  //acqTotAppCommCnt
    'N',  //logAcqTotAppCntComm
    'A',  //logacqTotAppTelkomAmt
    'N',  //logacqTotAppTelkomCnt
    'A',  //logacqTotAppSatelindoAmt
    'N',  //logacqTotAppSatelindoCnt
    'A',  //logacqTotAppTelkomselAmt
    'N',  //logacqTotAppTelkomselCnt
    'A',  //logacqTotAppExcelcomAmt
    'N',  //logacqTotAppExcelcomCnt
    'A',  //logacqTotAppEsiaAmt
    'N',  //logacqTotAppEsiaCnt
    'A',  //logacqTotAppPLNAmt
    'N',  //logacqTotAppPLNCnt
    'A',  //logacqTotAppFirstMediaAmt
    'N',  //logacqTotAppFirstMediaCnt
    'A',  //logacqTotAppIndovisionAmt
    'N',  //logacqTotAppIndovisionCnt
    'A',  //logacqTotAppOtoMultiAmt
    'N',  //logacqTotAppOtoMultiCnt
    'A',  //logacqTotAppMAtmAmt
    'N',  //logacqTotAppMAtmCnt
    'A',  //logacqTotAppMINIATMAmt
    'A',  //logAcqTotAppDbAmt
    'N',  //logAcqTotAppDbCnt
    'A',  //logAcqTotAppVoidAmt
    'N',  //logAcqTotAppVoidCnt
    'A',  //logAcqTotAppTipAmt
    'N',  //logAcqTotAppTipCnt
    'A',  //acqPriTxnPhnSrv
    'A',  //acqSecTxnPhnSrv
    'A',  //acqPriStlPhnSrv
    'A',  //acqSecStlPhnSrv
    'A',  //acqPriTxnIPSrv
    'A',  //acqSecTxnIPSrv
    'A',  //acqPriStlIPSrv
    'A',  //acqSecStlIPSrv
    'A',  //acqMasterKey1
    'A',  //acqMasterKey2
    'A',  //acqWorkingKey
    'A',  //acqPinKey
    'N',  //acqPendingSettle
    'N',  //acqLogonFlag
    'N',  //acqFlagCountTrx
};

static tRecord recIss; //Issuer Structure
static tTable tabIss;
static tContainer cntIss;
static word issLen[DIM(issBeg,issEnd)]= {
    sizeof(byte),  //issID
    lenIssRef,  //issRef
    sizeof(byte),  //issOpt1
    sizeof(byte),  //issOpt2
    sizeof(byte),  //issOpt3
    sizeof(byte),  //issOpt4
    sizeof(byte),  //issDefAcct
    sizeof(word),  //issFloorLimit
    sizeof(byte),  //issOpt5
    sizeof(byte),  //issPinOpt
    lenTotAmt,  //issTotAppDbAmt
    sizeof(word),  //issTotAppDbCnt
    lenTotAmt,  //issTotAppCrAmt
    sizeof(word),  //issTotAppCrCnt
    lenTotAmt,  //issTotAppTpAmt
    sizeof(word),  //issTotAppTpCnt
    lenTotAmt,  //issTotAppSaleAmt
    sizeof(word),  //issTotAppSaleCnt
    lenTotAmt,  //issTotAppRefundAmt
    sizeof(word),  //issTotAppRefundCnt
    lenTotAmt,  //issTotAppOfflineAmt
    sizeof(word),  //issTotAppOfflineCnt
    lenTotAmt,  //issTotAppManualAmt
    sizeof(word),  //issTotAppManualCnt
    lenTotAmt,  //issTotAppVoidAmt
    sizeof(word),  //issTotAppVoidCnt
    lenTotAmt,  //issTotAppAmtPrepaid
    sizeof(word),  //issTotAppPrepaidCnt
    lenTotAmt,  //issTotAppAmtPrepaidUpdate
    sizeof(word),  //issTotAppPrepaidCntUpdate
    lenTotAmt,  //issTotAppAmtTelkom
    sizeof(word),  //issTotAppCntTelkom
    lenTotAmt,  //issTotAppAmtSatelindo
    sizeof(word),  //issTotAppCntSatelindo
    lenTotAmt,  //issTotAppAmtTelkomsel
    sizeof(word),  //issTotAppCntTelkomsel
    lenTotAmt,  //issTotAppAmtExcelcom
    sizeof(word),  //issTotAppCntExcelcom
    lenTotAmt,  //issTotAppAmtEsia
    sizeof(word),  //issTotAppCntEsia
    lenTotAmt,  //issTotAppAmtPLN
    sizeof(word),  //issTotAppCntPLN
    lenTotAmt,  //issTotAppAmtFirstMedia
    sizeof(word),  //issTotAppCntFirstMedia
    lenTotAmt,  //issTotAppAmtIndovision
    sizeof(word),  //issTotAppCntIndovision
    lenTotAmt,  //issTotAppAmtOtoMulti
    sizeof(word),  //issTotAppCntOtoMulti
    lenTotAmt,  //issTotAppAmtMAtm
    sizeof(word),  //issTotAppCntMAtm
    lenTotAmt,  //issTotAppPrepaidAmtGP
    sizeof(word),  //issTotAppPrepaidCntGP
    lenTotAmt,  //issTotAppAmtMiniAtm
    lenTotAmt,  //issTotAppAmtTunai
    sizeof(word),  //issTotAppCntTunai
    lenTotAmt,  //issTotAppAmtTransfer
    sizeof(word),  //issTotAppCntTransfer
    lenTotAmt,  //issTotAppAmtCC
    sizeof(word),  //issTotAppCntCC
    lenTotAmt,  //issTotAppAmtTransferUSD
    sizeof(word),  //issTotAppCntTransferUSD
    lenTotAmt,  //issTotAppAmtTransferSGD
    sizeof(word),  //issTotAppCntTransferSGD
    lenTotAmt,  //issTotAppAmtTransferJPN
    sizeof(word),  //issTotAppCntTransferJPN
    sizeof(word),  //issTotAppCntComm
    sizeof(byte),  //issAccSelect
    sizeof(byte),  //issEMVFallback
    sizeof(byte),  //issManual
    sizeof(byte),  //issExpiryDatReq
    sizeof(byte),  //issOffline
    sizeof(byte),  //issRefferalDial
    sizeof(byte),  //issProductCod
    sizeof(byte),  //issAdjust
    sizeof(byte),  //issDoModPAN
    sizeof(byte),  //issROCNumReq
    sizeof(byte),  //issPrintReceipt
    sizeof(byte),  //issCapTxns
    sizeof(byte),  //issCheckExpOff
    sizeof(byte),  //issRefund
    sizeof(byte),  //issPreauth
    sizeof(byte),  //issVoid
    sizeof(byte),  //issAdditionPrompts
    sizeof(byte),  //issCheckExpAll
    sizeof(byte),  //issCashOut
    sizeof(byte),  //issTrack1
    sizeof(byte),  //issBalance
    sizeof(byte),  //issErrorReceipt
    sizeof(byte),  //issOfflineROC
    sizeof(byte),  //issExtServiceCod
    sizeof(byte),  //issFullPAN
    sizeof(byte),  //issExpiryDate
    sizeof(byte),  //issManEntryCVV
    lenTotAmt,  //issTotAppAmtMOnUs
    sizeof(word),  //issTotAppCntMOnUs
    lenTotAmt,  //issTotAppAmtVOnUs
    sizeof(word),  //issTotAppCntVOnUs
    lenTotAmt,  //issTotAppAmtMOffUs
    sizeof(word),  //issTotAppCntMOffUs
    lenTotAmt,  //issTotAppAmtVOffUs
    sizeof(word),  //issTotAppCntVOffUs
    lenTotAmt,  //issTotAppVoidAmtMOnUs
    sizeof(word),  //issTotAppVoidCntMOnUs
    lenTotAmt,  //issTotAppVoidAmtVOnUs
    sizeof(word),  //issTotAppVoidCntVOnUs
    lenTotAmt,  //issTotAppVoidAmtMOffUs
    sizeof(word),  //issTotAppVoidCntMOffUs
    lenTotAmt,  //issTotAppVoidAmtVOffUs
    sizeof(word),  //issTotAppVoidCntVOffUs
    lenTotAmt,  //issTotAppTipAmtMOnUs
    lenTotAmt,  //issTotAppTipAmtVOnUs
    lenTotAmt,  //issTotAppTipAmtMOffUs
    lenTotAmt,  //issTotAppTipAmtVOffUs
};
static word issMap[DIM(issBeg,issEnd)];
static char issFmt[DIM(issBeg,issEnd)]= {
    'N',  //issID
    'A',  //issRef
    'N',  //issOpt1
    'N',  //issOpt2
    'N',  //issOpt3
    'N',  //issOpt4
    'N',  //issDefAcct
    'N',  //issFloorLimit
    'N',  //issOpt5
    'N',  //issPinOpt
    'A',  //issTotAppDbAmt
    'N',  //issTotAppDbCnt
    'A',  //issTotAppCrAmt
    'N',  //issTotAppCrCnt
    'A',  //issTotAppTpAmt
    'N',  //issTotAppTpCnt
    'A',  //issTotAppSaleAmt
    'N',  //issTotAppSaleCnt
    'A',  //issTotAppRefundAmt
    'N',  //issTotAppRefundCnt
    'A',  //issTotAppOfflineAmt
    'N',  //issTotAppOfflineCnt
    'A',  //issTotAppManualAmt
    'N',  //issTotAppManualCnt
    'A',  //issTotAppVoidAmt
    'N',  //issTotAppVoidCnt
    'A',  //issTotAppAmtPrepaid
    'N',  //issTotAppPrepaidCnt
    'A',  //issTotAppAmtPrepaidUpdate
    'N',  //issTotAppPrepaidCntUpdate
    'A',  //issTotAppAmtTelkom
    'N',  //issTotAppCntTelkom
    'A',  //issTotAppAmtSatelindo
    'N',  //issTotAppCntSatelindo
    'A',  //issTotAppAmtTelkomsel
    'N',  //issTotAppCntTelkomsel
    'A',  //issTotAppAmtExcelcom
    'N',  //issTotAppCntExcelcom
    'A',  //issTotAppAmtEsia
    'N',  //issTotAppCntEsia
    'A',  //issTotAppAmtPLN
    'N',  //issTotAppCntPLN
    'A',  //issTotAppAmtFirstMedia
    'N',  //issTotAppCntFirstMedia
    'A',  //issTotAppAmtIndovision
    'N',  //issTotAppCntIndovision
    'A',  //issTotAppAmtOtoMulti
    'N',  //issTotAppCntOtoMulti
    'A',  //issTotAppAmtMAtm
    'N',  //issTotAppCntMAtm
    'A',  //issTotAppPrepaidAmtGP
    'N',  //issTotAppPrepaidCntGP
    'A',  //issTotAppAmtMiniAtm
    'A',  //issTotAppAmtTunai
    'N',  //issTotAppCntTunai
    'A',  //issTotAppAmtTransfer
    'N',  //issTotAppCntTransfer
    'A',  //issTotAppAmtCC
    'N',  //issTotAppCntCC
    'A',  //issTotAppAmtTransferUSD
    'N',  //issTotAppCntTransferUSD
    'A',  //issTotAppAmtTransferSGD
    'N',  //issTotAppCntTransferSGD
    'A',  //issTotAppAmtTransferJPN
    'N',  //issTotAppCntTransferJPN
    'N',  //issTotAppCntComm
    'N',  //issAccSelect
    'N',  //issEMVFallback
    'N',  //issManual
    'N',  //issExpiryDatReq
    'N',  //issOffline
    'N',  //issRefferalDial
    'N',  //issProductCod
    'N',  //issAdjust
    'N',  //issDoModPAN
    'N',  //issROCNumReq
    'N',  //issPrintReceipt
    'N',  //issCapTxns
    'N',  //issCheckExpOff
    'N',  //issRefund
    'N',  //issPreauth
    'N',  //issVoid
    'N',  //issAdditionPrompts
    'N',  //issCheckExpAll
    'N',  //issCashOut
    'N',  //issTrack1
    'N',  //issBalance
    'N',  //issErrorReceipt
    'N',  //issOfflineROC
    'N',  //issExtServiceCod
    'N',  //issFullPAN
    'N',  //issExpiryDate
    'N',  //issManEntryCVV
    'A',  //issTotAppAmtMOnUs
    'N',  //issTotAppCntMOnUs
    'A',  //issTotAppAmtVOnUs
    'N',  //issTotAppCntVOnUs
    'A',  //issTotAppAmtMOffUs
    'N',  //issTotAppCntMOffUs
    'A',  //issTotAppAmtVOffUs
    'N',  //issTotAppCntVOffUs
    'A',  //issTotAppVoidAmtMOnUs
    'N',  //issTotAppVoidCntMOnUs
    'A',  //issTotAppVoidAmtVOnUs
    'N',  //issTotAppVoidCntVOnUs
    'A',  //issTotAppVoidAmtMOffUs
    'N',  //issTotAppVoidCntMOffUs
    'A',  //issTotAppVoidAmtVOffUs
    'N',  //issTotAppVoidCntVOffUs
    'A',  //issTotAppTipAmtMOnUs
    'A',  //issTotAppTipAmtVOnUs
    'A',  //issTotAppTipAmtMOffUs
    'A',  //issTotAppTipAmtVOffUs
};

static tRecord recApp; //application parameters record
static tContainer cntApp;
static word appLen[DIM(appBeg,appEnd)]= {
    lenCmpDat,  //appCmpDat
    lenCmpTim,  //appCmpTim
    lenEndTime,  //appEndTime
    lenApn,  //appGprsApn
    lenChn,  //appChn
    lenSrv,  //appSrv
    sizeof(byte),  //appSrvAtt
    lenPabx,  //appPabx
    sizeof(byte),  //appTonePulse
    sizeof(byte),  //appToneDetect
    lenPrefix,  //appPrefix
    lenPwd,  //appMrcPwd
    lenPwd,  //appAdmPwd
    lenPwd,  //appAccCode
    sizeof(byte),  //appExp
    lenTid,  //appTid
    lenMid,  //appMid
    sizeof(byte),  //appAmtFmt
    sizeof(byte),  //appDefTra
    sizeof(byte),  //appTermOpt1
    sizeof(byte),  //appTermOpt2
    sizeof(byte),  //appTermOpt5
    sizeof(byte),  //appLocOpt
    lenCurrSign,  //appCurrSign
    sizeof(byte),  //appConnType
    sizeof(byte),  //appComType
    lenPwd,  //appVoidPwd
    lenPwd,  //appRefPwd
    lenPwd,  //appSetlPwd
    sizeof(byte),  //appEMSale
    sizeof(byte),  //appEMRefund
    sizeof(byte),  //appEMOffline
    sizeof(byte),  //appEMCash
    sizeof(byte),  //appEMPreAuth
    sizeof(byte),  //appEMCrdVrfy
    sizeof(byte),  //appEMBalance
    sizeof(byte),  //appGPRSFlag
    lenNII,  //appNII
    lenSrv,  //appPriSrv
    sizeof(byte),  //appPriAtt
    lenSrv,  //appSecSrv
    sizeof(byte),  //appSecAtt
    sizeof(byte),  //appDialOpt
    lenMid,  //appRefNum
    sizeof(byte),  //appBaudRate
    sizeof(byte),  //appTmsBufSize
    sizeof(byte),  //appTmsDhcp
    lenSrv,  //appIpAdd
    lenSrv,  //appSecIpAdd
    lenSrv,  //appSubMask
    lenSrv,  //appDefGateway
    lenCrdInpCtl,  //appCrdInpCtl
    sizeof(byte),  //appPinKeyLoc
    sizeof(byte),  //appMKeyLoc
    sizeof(word),  //appDefRxTO
    sizeof(word),  //appDefICTO
    sizeof(word),  //appDefConTO
    lenTraName,  //apptraSale
    lenTraName,  //apptraOSale
    lenTraName,  //apptraOffline
    lenTraName,  //apptraPreAuth
    lenTraName,  //apptraVoid
    lenTraName,  //apptraRefund
    lenTraName,  //apptraAdjust
    lenTraName,  //apptraManual
    lenTraName,  //appTenor1
    lenTraName,  //appTenor3
    lenTraName,  //appTenor6
    lenTraName,  //appTenor9
    lenTraName,  //appTenor12
    lenTraName,  //appTenor18
    lenTraName,  //appTenor24
    1,  //apptpduHead
    2,  //apptpduModem
    2,  //apptpduTCPIP
    2,  //apptpduRS232
    1+lenTrnCurCod,  //emvTrnCurCod
    1+lenTrnCurExp,  //emvTrnCurExp
    1+lenMrcCatCod,  //emvMrcCatCod
    1+lenTrmCntCod,  //emvTrmCntCod
    1+lenTID,  //emvTrmId
    1+lenTrmCap,  //emvTrmCap
    1+lenEmvTrmTyp,  //emvTrmTyp
    1+lenAddTrmCap,  //emvAddTrmCap
    1+lenVlpSupInd,  //emvVlpSupInd
    1+lenVlpTrmLim,  //emvVlpTrmLim
    1+lenLstRspCod,  //emvLstRspCod
    1+lenIFDSerNum,  //emvIFDSerNum
    1+2,  //emvTRMOverpassAIP
    sizeof(byte),  //appServiceCode
    sizeof(byte),  //appFallBackMod
    128,  //appPPPNbr
    16,  //appBfKey
    sizeof(byte),  //appBlowFish
    8,  //appAftTMSKey
    sizeof(byte),  //appICT220
    sizeof(byte),  //appSettleInd
    6,  //appBf
    sizeof(word),  //appPANBlockBegin
    sizeof(word),  //appPANBlockEnd
    lenCurrSign+2,  //appCurrSignSpaces
    700,  //appRequest
    sizeof(word),  //appReqLen
    700,  //appRespon
    sizeof(word),  //appRspLen
    4,  //appPassTel
    700,  //appBit57
    sizeof(word),  //appBit57Len
    700,  //appBit57Rsp
    sizeof(word),  //appBit57RspLen
    1+lenAppPrfNam,  //appAppPrfNam
    1+lenEmvPAN,  //emvPAN
    1+lenTrnDat,  //emvTrnDat
    1+lenTrnTim,  //emvTrnTim
    1+lenTrnTyp,  //emvTrnTyp
    1+lenAmtBin,  //emvAmtBin
    1+lenAmtNum,  //emvAmtOthNum
    1+lenAmtBin,  //emvAmtOthBin
    1+lenPANSeq,  //emvPANSeq
    1+lenTVR,  //emvIACDft
    1+lenTVR,  //emvIACDnl
    1+lenTVR,  //emvIACOnl
    1+lenAIP,  //emvAIP
    1+lenTVR,  //emvTVR
    1+lenTSI,  //emvTSI
    1+lenCVMRes,  //emvCVMRes
    1+lenIAD,  //emvIAD
    1+lenRspCod,  //emvRspCod
    1+2,  //emvACReq1
    1+64,  //emvACReq2
    2,  //traACReq2
    1+2,  //emvACRsp1
    1+2,  //emvACRsp2
    1+7,  //emvLstCmdRsp
    1+4,  //traLstCmdRsp
    1+lenIssTrnCrt,  //emvIssTrnCrt
    1+lenATC,  //emvATC
    1+lenUnpNum,  //emvUnpNum
    1+lenAmtNum,  //emvAmtNum
    1+lenAmtBin,  //emvAmtPrv
    1+lenCapkIdx,  //emvCapkIdx
    lenAmt,  //emvAppTraAmt
    sizeof(byte),  //appLockFlag
    8,  //appUserId
    sizeof(byte),  //appAfterTMS
    sizeof(word),  //appGetTick
    lenTmsRefNum,  //appTmsRefNum
    1+lenDFNam,  //emvDFNam
    4,  //appVersion
    6,  //appSoftName
    16,  //appDisplayCd
    3,  //appLtmkAcqID
    8,  //appVendorID
    112,  //appLTMKDATA
    128,  //appModulusRSA
    16,  //appKeySessionTle
    lenNII,  //appNiiLTMK
    80,  //appKMSLTMKDATA
    48,  //appLTMK
    104,  //appLTWKTID1
    8,  //appTidTle
    6,  //appExponent
    8+1,  //appKeySessionSAM
    sizeof(byte),  //appTleSet
    28,  //appBit58
    sizeof(byte),  //appTxnVoidBfr
    sizeof(word),  //appIdxBtcUpl
    sizeof(word),  //appNbrTxnVoidBfr
    2,  //CurDay
    sizeof(byte),  //appCntReceipt
    lenNII,  //appNIIMntr
    4,  //appto
    4,  //apptoidle
    4,  //apptoTFHr
    lenSrv,  //appPriMonSrv
    sizeof(byte),  //appPriMonAtt
    lenSrv,  //appSecMonSrv
    sizeof(byte),  //appSecMonAtt
    20,  //appChipUIDSAM
    3,  //appCIN
    7,  //appCHIP_UID
    2,  //appDATESAM
    4,  //appSEQ_NO
    16,  //appCHIP_VERSION
    16,  //appENGINE_VERSION
    1,  //appFlagSam
    1,  //appFlagSamPrepaid
    1,  //appFlagRevPrepaid
    1,  //appFlagTokenPrepaid
    sizeof(byte),  //appFlagPowerfailure
    47,  //appGracePeriod
    24,  //appPinSamCard
    sizeof(byte),  //appDisplayVivoTech
    76,  //appRekMerchant
    5,  //appTimeSet
    sizeof(byte),  //appFlagSettle
    6,  //appLastAutCodPrepaid
    26,  //appLastTCCode
    12,  //appTerminalType
    6,  //appDateMonitoring
    sizeof(byte),  //appFlagEDCMon
    6,  //appDateReInitRetryEDCMon
    sizeof(word),  //appTimeEdcMon
    lenRrn,  //appRrn
    sizeof(byte),  //appFlagDownloadLTWK
    sizeof(byte),  //appFlagInit
    1,  //appCtrlVersion
};
static word appMap[DIM(appBeg,appEnd)];
static char appFmt[DIM(appBeg,appEnd)]= {
    'A',  //appCmpDat
    'A',  //appCmpTim
    'A',  //appEndTime
    'A',  //appGprsApn
    'A',  //appChn
    'A',  //appSrv
    'N',  //appSrvAtt
    'A',  //appPabx
    'N',  //appTonePulse
    'N',  //appToneDetect
    'A',  //appPrefix
    'A',  //appMrcPwd
    'A',  //appAdmPwd
    'A',  //appAccCode
    'N',  //appExp
    'A',  //appTid
    'A',  //appMid
    'N',  //appAmtFmt
    'N',  //appDefTra
    'N',  //appTermOpt1
    'N',  //appTermOpt2
    'N',  //appTermOpt5
    'N',  //appLocOpt
    'A',  //appCurrSign
    'N',  //appConnType
    'N',  //appComType
    'A',  //appVoidPwd
    'A',  //appRefPwd
    'A',  //appSetlPwd
    'N',  //appEMSale
    'N',  //appEMRefund
    'N',  //appEMOffline
    'N',  //appEMCash
    'N',  //appEMPreAuth
    'N',  //appEMCrdVrfy
    'N',  //appEMBalance
    'N',  //appGPRSFlag
    'A',  //appNII
    'A',  //appPriSrv
    'N',  //appPriAtt
    'A',  //appSecSrv
    'N',  //appSecAtt
    'N',  //appDialOpt
    'A',  //appRefNum
    'N',  //appBaudRate
    'N',  //appTmsBufSize
    'N',  //appTmsDhcp
    'A',  //appIpAdd
    'A',  //appSecIpAdd
    'A',  //appSubMask
    'A',  //appDefGateway
    'A',  //appCrdInpCtl
    'N',  //appPinKeyLoc
    'N',  //appMKeyLoc
    'N',  //appDefRxTO
    'N',  //appDefICTO
    'N',  //appDefConTO
    'A',  //apptraSale
    'A',  //apptraOSale
    'A',  //apptraOffline
    'A',  //apptraPreAuth
    'A',  //apptraVoid
    'A',  //apptraRefund
    'A',  //apptraAdjust
    'A',  //apptraManual
    'A',  //appTenor1
    'A',  //appTenor3
    'A',  //appTenor6
    'A',  //appTenor9
    'A',  //appTenor12
    'A',  //appTenor18
    'A',  //appTenor24
    'A',  //apptpduHead
    'A',  //apptpduModem
    'A',  //apptpduTCPIP
    'A',  //apptpduRS232
    'B',  //emvTrnCurCod
    'B',  //emvTrnCurExp
    'B',  //emvMrcCatCod
    'B',  //emvTrmCntCod
    'B',  //emvTrmId
    'B',  //emvTrmCap
    'B',  //emvTrmTyp
    'B',  //emvAddTrmCap
    'B',  //emvVlpSupInd
    'B',  //emvVlpTrmLim
    'B',  //emvLstRspCod
    'B',  //emvIFDSerNum
    'B',  //emvTRMOverpassAIP
    'N',  //appServiceCode
    'N',  //appFallBackMod
    'A',  //appPPPNbr
    'A',  //appBfKey
    'N',  //appBlowFish
    'A',  //appAftTMSKey
    'N',  //appICT220
    'N',  //appSettleInd
    'A',  //appBf
    'N',  //appPANBlockBegin
    'N',  //appPANBlockEnd
    'A',  //appCurrSignSpaces
    'A',  //appRequest
    'N',  //appReqLen
    'A',  //appRespon
    'N',  //appRspLen
    'A',  //appPassTel
    'A',  //appBit57
    'N',  //appBit57Len
    'A',  //appBit57Rsp
    'N',  //appBit57RspLen
    'B',  //appAppPrfNam
    'B',  //emvPAN
    'B',  //emvTrnDat
    'B',  //emvTrnTim
    'B',  //emvTrnTyp
    'B',  //emvAmtBin
    'B',  //emvAmtOthNum
    'B',  //emvAmtOthBin
    'B',  //emvPANSeq
    'B',  //emvIACDft
    'B',  //emvIACDnl
    'B',  //emvIACOnl
    'B',  //emvAIP
    'B',  //emvTVR
    'B',  //emvTSI
    'B',  //emvCVMRes
    'B',  //emvIAD
    'B',  //emvRspCod
    'B',  //emvACReq1
    'B',  //emvACReq2
    'A',  //traACReq2
    'B',  //emvACRsp1
    'B',  //emvACRsp2
    'B',  //emvLstCmdRsp
    'B',  //traLstCmdRsp
    'B',  //emvIssTrnCrt
    'B',  //emvATC
    'B',  //emvUnpNum
    'B',  //emvAmtNum
    'B',  //emvAmtPrv
    'B',  //emvCapkIdx
    'A',  //emvAppTraAmt
    'N',  //appLockFlag
    'A',  //appUserId
    'N',  //appAfterTMS
    'N',  //appGetTick
    'A',  //appTmsRefNum
    'B',  //emvDFNam
    'A',  //appVersion
    'A',  //appSoftName
    'A',  //appDisplayCd
    'A',  //appLtmkAcqID
    'A',  //appVendorID
    'A',  //appLTMKDATA
    'A',  //appModulusRSA
    'A',  //appKeySessionTle
    'A',  //appNiiLTMK
    'A',  //appKMSLTMKDATA
    'A',  //appLTMK
    'A',  //appLTWKTID1
    'A',  //appTidTle
    'A',  //appExponent
    'A',  //appKeySessionSAM
    'N',  //appTleSet
    'A',  //appBit58
    'N',  //appTxnVoidBfr
    'N',  //appIdxBtcUpl
    'N',  //appNbrTxnVoidBfr
    'A',  //CurDay
    'N',  //appCntReceipt
    'A',  //appNIIMntr
    'A',  //appto
    'A',  //apptoidle
    'A',  //apptoTFHr
    'A',  //appPriMonSrv
    'N',  //appPriMonAtt
    'A',  //appSecMonSrv
    'N',  //appSecMonAtt
    'A',  //appChipUIDSAM
    'A',  //appCIN
    'A',  //appCHIP_UID
    'A',  //appDATESAM
    'A',  //appSEQ_NO
    'A',  //appCHIP_VERSION
    'A',  //appENGINE_VERSION
    'A',  //appFlagSam
    'A',  //appFlagSamPrepaid
    'A',  //appFlagRevPrepaid
    'A',  //appFlagTokenPrepaid
    'N',  //appFlagPowerfailure
    'A',  //appGracePeriod
    'A',  //appPinSamCard
    'N',  //appDisplayVivoTech
    'A',  //appRekMerchant
    'A',  //appTimeSet
    'N',  //appFlagSettle
    'A',  //appLastAutCodPrepaid
    'A',  //appLastTCCode
    'A',  //appTerminalType
    'A',  //appDateMonitoring
    'N',  //appFlagEDCMon
    'A',  //appDateReInitRetryEDCMon
    'N',  //appTimeEdcMon
    'A',  //appRrn
    'N',  //appFlagDownloadLTWK
    'N',  //appFlagInit
    'A',  //appCtrlVersion
};

static tRecord recTra; //transaction related data situated in volatile memory
static tContainer cntTra;
static word traLen[DIM(traBeg,traEnd)]= {
    lenDatTim,  //traDatTim
    sizeof(word),  //traMnuItm
    dspW,  //traCtx
    lenTrk2,  //traTrk2
    lenPan,  //traPan
    lenExpDat,  //traExpDat
    lenAmt,  //traAmt
    lenCardTransType,  //traTransType
    lenCardTransType,  //traCardType
    lenAmt,  //traTipAmt
    20,  //traTotAmt
    20,  //traDspAmt
    lenAutCod,  //traAutCod
    lenRspCod,  //traRspCod
    lenRrn,  //traRrn
    sizeof(byte),  //traTxnType
    dspW,  //traIssName
    dspW,  //traTrk21
    dspW,  //traTrk22
    sizeof(byte),  //traCrdSeq
    sizeof(byte),  //traBinIdx
    sizeof(byte),  //traAcqIdx
    sizeof(byte),  //traIssIdx
    lenSrv,  //traSrv
    dspW,  //traTCPIPprm
    dspW,  //traPriSec
    dspW,  //traIPConfig
    1+lenPinBlk,  //traPinBlk
    sizeof(byte),  //traPinReq
    sizeof(byte),  //traSgnReq
    lenTrk2,  //traTrk1
    sizeof(word),  //traMnuItmBeforeOffline
    sizeof(byte),  //traTxnTypeBeforeOffline
    sizeof(word),  //traIdx
    sizeof(word),  //traLogTotalCount
    lenName,  //traTypeName
    4,  //traTypeCurName
    3,  //traLogTxnTtlCnt
    lenAmt,  //traLogTotalAmount
    lenName,  //traAcqName
    lenInvNum,  //traFindRoc
    sizeof(byte),  //traVoidFlag
    20,  //traFmtAmt
    lenAmt,  //traFmtTip
    sizeof(byte),  //traVoidFlagContext
    sizeof(word),  //traMnuItmContext
    lenDatTim,  //traDatTimContext
    sizeof(byte),  //traBinIdxContext
    sizeof(byte),  //traAcqIdxContext
    sizeof(byte),  //traIssIdxContext
    lenPan,  //traPanContext
    lenExpDat,  //traExpDatContext
    lenTrk2,  //traTrk2Context
    lenAutCod,  //traAutCodContext
    lenAmt,  //traAmtContext
    lenAmt,  //traTipAmtContext
    lenRrn,  //traRrnContext
    sizeof(char),  //traEntModContext
    sizeof(byte),  //traConCodeContext
    lenCardTransType,  //traCardTypeContext
    sizeof(byte),  //traEmvFullFlagContext
    sizeof(byte),  //traTxnTypeContext
    sizeof(byte),  //traTxnIdContext
    sizeof(byte),  //traLocTypeContext
    lenCardTransType,  //traTransTypeContext
    sizeof(byte),  //traTmsMsg
    sizeof(byte),  //traTmsMreRec
    lenFleNme,  //traTmsEmvFleNme
    1+lenFleHdl,  //traTmsEmvFleHdl
    sizeof(card),  //traTmsEmvFleOff
    sizeof(card),  //traTmsEmvFleSze
    sizeof(word),  //traTmsEmvFlechnlen
    sizeof(byte),  //traTmsDnlWidEmv
    lenSrv,  //traPriIpBuf
    lenSrv,  //traPriPortBuf
    lenSrv,  //traSecIpBuf
    lenSrv,  //traSecPortBuf
    lenDatTim,  //traFmtDate
    lenDatTim,  //traFmtTime
    sizeof(card),  //traInvNum
    dspW,  //traRspDspLin1
    dspW,  //traRspDspLin2
    lenAppPrfNam,  //traAppPrfNam
    1+lenAppPrfNam,  //emvAppPrfNam
    1+lenAppPrfNam,  //emvAppLbl
    1+lenTrnSeqCnt,  //emvTrnSeqCnt
    1+lenEmvTrk2,  //emvTrk2
    1+lenEmvExpDat,  //emvExpDat
    1+lenCVM,  //emvCVM
    1+lenCrdAvn,  //emvCrdAvn
    1+lenChdNam,  //emvChdNam
    1+lenLanPrf,  //emvLanPrf
    1+lenRSAKeyExp,  //emvRSAKeyExp
    1+lenRSAKey,  //emvRSAKey
    1+lenCVMOutRes,  //emvCVMOutRes
    1+lenFrcOnl,  //emvFrcOnl
    1+lenHotLst,  //emvHotLst
    1+lenCID,  //emvCID
    1+lenTrmDcs,  //emvTrmDc1
    1+lenTrmDcs,  //emvTrmDc2
    1+lenOnlSta,  //emvOnlSta
    1+lenAuthRes,  //emvAuthRes
    1+lenCommOk,  //emvCommOk
    1+lenIssAutDta,  //emvIssAutDta
    1+lenAutCod,  //emvAutCod
    1+lenIssSc1,  //emvIssSc1
    1+lenIssSc2,  //emvIssSc2
    7,  //traEMSale
    10,  //traChipSwipe
    sizeof(byte),  //traTxnId
    lenPan,  //traBlockPan
    sizeof(byte),  //traTipFlag
    sizeof(byte),  //traFallback
    3,  //traSrvCod
    sizeof(byte),  //traEmvTrnType
    5,  //traExpDatFmt
    sizeof(byte),  //traCustFlag
    lenAutCod,  //traAutCodOff
    lenEmvICC,  //traEmvICC
    sizeof(byte),  //traInputPin
    sizeof(byte),  //traNeedLogon
    2,  //traRspBit13
    3,  //traRspBit12
    lenMti,  //traMti
    2,  //traPanSeq
    sizeof(byte),  //traEmvFullFlag
    sizeof(byte),  //traLoginFlag
    sizeof(byte),  //traIsSign
    32,  //traWorkingKey
    lenTid,  //traSerNum
    37,  //traLeMsg
    8,  //traMAC
    sizeof(byte),  //traMsgFlag
    sizeof(byte),  //traBit23On
    16,  //traLTWKDEK
    sizeof(word),  //traMnuItmVoid
    6,  //traTimeSend
    13,  //traAppName
    22,  //traInvTransType
    20,  //traLine3
    sizeof(byte),  //traBinReq
    6,  //traPinInput
    128,  //traBit48PwrBuy
    20,  //traAmtMonthly
    9,  //traMonth
    sizeof(byte),  //traEmvReqFlag
    sizeof(word),  //traMnuItmTenor
    16,  //traPwrBuyType
    sizeof(byte),  //traReader
    1,  //traSAMPreStatus
    47,  //traSAMTransactionReport
    12,  //traAmtTopUp
    12,  //traAmtPrepaid
    37,  //traTrk2Prepaid
    256,  //traInquBit48Prepaid
    128,  //traBit58
    256,  //traSAMHost
    16,  //traTrkPrepaidPrint
    20,  //traTrkPrepaidTapPrint
    25,  //traTrkPrepaidSwipePrint
    256,  //traServerAuthPrepaid
    16,  //traHastPrepaid
    24,  //traTidTxr
    16,  //traTidIns
    32,  //traCardNo
    20,  //traPayment
    20,  //traBalance
    2,  //traInsId
    20,  //traSaldoAKhir
    20,  //traSaldoAwal
    26,  //traTCCode
    6,  //traAppCode
    15,  //tramerchantAmt
    15,  //traIssuerAmt
    15,  //traPoolingAmt
    15,  //traSaleAmT
    15,  //traPrepaidTotal
    256,  //traRevBit48Prepaid
    256,  //traRevBit58Prepaid
    sizeof(word),  //traLogTotalCounTopup
    lenAmt,  //traLogTotalAmountTopup
    sizeof(byte),  //traStateFlag
    sizeof(word),  //traLogTotalCounTelkom
    lenAmt,  //traLogTotalAmountTelkom
    sizeof(word),  //traLogTotalCounSatelindo
    lenAmt,  //traLogTotalAmountSatelindo
    sizeof(word),  //traLogTotalCounTelkomsel
    lenAmt,  //traLogTotalAmountTelkomsel
    sizeof(word),  //traLogTotalCounExcelcom
    lenAmt,  //traLogTotalAmountExcelcom
    sizeof(word),  //traLogTotalCounEsia
    lenAmt,  //traLogTotalAmountEsia
    sizeof(word),  //traLogTotalCounPLN
    lenAmt,  //traLogTotalAmountPLN
    sizeof(word),  //traLogTotalCounFirstMedia
    lenAmt,  //traLogTotalAmountFirstMedia
    sizeof(word),  //traLogTotalCounIndovision
    lenAmt,  //traLogTotalAmountIndovision
    sizeof(word),  //traLogTotalCounOtoMulti
    lenAmt,  //traLogTotalAmountOtoMulti
    sizeof(word),  //traLogTotalCounMAtm
    lenAmt,  //traLogTotalAmountMAtm
    lenAmt,  //traLogTotalAmountMINIAtm
    128,  //traRspBit58ServerAuth
    sizeof(word),  //traLogTotalCounComm
    19,  //traAccDest
    3,  //traCode
    13,  //traSourceBuyRate
    13,  //traSourceSaleRate
    13,  //traDestBuyRate
    13,  //traDestSaleRate
    3,  //traCodeDest
    16,  //traTunai
    lenAmt,  //traAmtIDR
    sizeof(word),  //traLogTotalCounTunai
    lenAmt,  //traLogTotalAmountTunai
    sizeof(word),  //traLogTotalCounTransfer
    lenAmt,  //traLogTotalAmountTransfer
    sizeof(word),  //traLogTotalCounCC
    lenAmt,  //traLogTotalAmountCC
    24,  //traLogTotalAmountTransferUSD
    sizeof(word),  //traLogTotalCounTransferUSD
    24,  //traLogTotalAmountTransferSGD
    sizeof(word),  //traLogTotalCounTransferSGD
    24,  //traLogTotalAmountTransferJPN
    sizeof(word),  //traLogTotalCounTransferJPN
    sizeof(byte),  //traPWCVoidFlag
    lenCardTransType ,  //traCardTypeTBM
    sizeof(byte),  //traAlreadyConnect
    lenInvNum,  //traCurBat
    1+lenAID,  //traEmvAid
    1+lenPrcCod,  //traPrcCod
    6,  //traTimeRecv
    sizeof(byte),  //traTcFlag
    lenTrack,  //traTrack1
    lenTrack,  //traTrack2
    lenTrack,  //traTrack3
    3,  //traCurValas
    sizeof(byte),  //traOnUsOffUs
    sizeof(byte),  //traFlagDBMCVS
    sizeof(card),  //traSTAN
    lenMti,  //traRspMti
    lenBitmap,  //traRspBitmap
    lenTid,  //traRspTID
    lenMid,  //traRspMID
    lenSTAN,  //traRspSTAN
    lenRrn,  //traRspRRN
    lenAutCod,  //traRspAutCod
    lenAmt,  //traRspAmount
    lenTrk2,  //traRspTrack2
    lenSTAN,  //traReqSTAN
    lenTid,  //traReqTID
    lenMid,  //traReqMID
    8,  //traCalcRspMAC
    8,  //traRspMAC
    lenAmt,  //traReqAmount
    lenBit1,  //traRspBitBeg
    lenBit1,  //traRspBit_1
    lenBit2,  //traRspBit_2
    lenBit3,  //traRspBit_3
    lenBit4,  //traRspBit_4
    lenBit5,  //traRspBit_5
    lenBit6,  //traRspBit_6
    lenBit7,  //traRspBit_7
    lenBit8,  //traRspBit_8
    lenBit9,  //traRspBit_9
    lenBit10,  //traRspBit_10
    lenBit11,  //traRspBit_11
    lenBit12,  //traRspBit_12
    lenBit13,  //traRspBit_13
    lenBit14,  //traRspBit_14
    lenBit15,  //traRspBit_15
    lenBit16,  //traRspBit_16
    lenBit17,  //traRspBit_17
    lenBit18,  //traRspBit_18
    lenBit19,  //traRspBit_19
    lenBit20,  //traRspBit_20
    lenBit21,  //traRspBit_21
    lenBit22,  //traRspBit_22
    lenBit23,  //traRspBit_23
    lenBit24,  //traRspBit_24
    lenBit25,  //traRspBit_25
    lenBit26,  //traRspBit_26
    lenBit27,  //traRspBit_27
    lenBit28,  //traRspBit_28
    lenBit29,  //traRspBit_29
    lenBit30,  //traRspBit_30
    lenBit31,  //traRspBit_31
    lenBit32,  //traRspBit_32
    lenBit33,  //traRspBit_33
    lenBit34,  //traRspBit_34
    lenBit35,  //traRspBit_35
    lenBit36,  //traRspBit_36
    lenBit37,  //traRspBit_37
    lenBit38,  //traRspBit_38
    lenBit39,  //traRspBit_39
    lenBit40,  //traRspBit_40
    lenBit41,  //traRspBit_41
    lenBit42,  //traRspBit_42
    lenBit43,  //traRspBit_43
    lenBit44,  //traRspBit_44
    lenBit45,  //traRspBit_45
    lenBit46,  //traRspBit_46
    lenBit47,  //traRspBit_47
    lenBit48,  //traRspBit_48
    lenBit49,  //traRspBit_49
    lenBit50,  //traRspBit_50
    lenBit51,  //traRspBit_51
    lenBit52,  //traRspBit_52
    lenBit53,  //traRspBit_53
    lenBit54,  //traRspBit_54
    lenBit55,  //traRspBit_55
    lenBit56,  //traRspBit_56
    lenBit57,  //traRspBit_57
    lenBit58,  //traRspBit_58
    lenBit59,  //traRspBit_59
    lenBit60,  //traRspBit_60
    lenBit61,  //traRspBit_61
    lenBit62,  //traRspBit_62
    lenBit63,  //traRspBit_63
    lenBit64,  //traRspBit_64
/////    lenBit103,  //traRspBit_103
    sizeof(word),  //traRspLBitBeg
    sizeof(word),  //traRspLBit_1
    sizeof(word),  //traRspLBit_2
    sizeof(word),  //traRspLBit_3
    sizeof(word),  //traRspLBit_4
    sizeof(word),  //traRspLBit_5
    sizeof(word),  //traRspLBit_6
    sizeof(word),  //traRspLBit_7
    sizeof(word),  //traRspLBit_8
    sizeof(word),  //traRspLBit_9
    sizeof(word),  //traRspLBit_10
    sizeof(word),  //traRspLBit_11
    sizeof(word),  //traRspLBit_12
    sizeof(word),  //traRspLBit_13
    sizeof(word),  //traRspLBit_14
    sizeof(word),  //traRspLBit_15
    sizeof(word),  //traRspLBit_16
    sizeof(word),  //traRspLBit_17
    sizeof(word),  //traRspLBit_18
    sizeof(word),  //traRspLBit_19
    sizeof(word),  //traRspLBit_20
    sizeof(word),  //traRspLBit_21
    sizeof(word),  //traRspLBit_22
    sizeof(word),  //traRspLBit_23
    sizeof(word),  //traRspLBit_24
    sizeof(word),  //traRspLBit_25
    sizeof(word),  //traRspLBit_26
    sizeof(word),  //traRspLBit_27
    sizeof(word),  //traRspLBit_28
    sizeof(word),  //traRspLBit_29
    sizeof(word),  //traRspLBit_30
    sizeof(word),  //traRspLBit_31
    sizeof(word),  //traRspLBit_32
    sizeof(word),  //traRspLBit_33
    sizeof(word),  //traRspLBit_34
    sizeof(word),  //traRspLBit_35
    sizeof(word),  //traRspLBit_36
    sizeof(word),  //traRspLBit_37
    sizeof(word),  //traRspLBit_38
    sizeof(word),  //traRspLBit_39
    sizeof(word),  //traRspLBit_40
    sizeof(word),  //traRspLBit_41
    sizeof(word),  //traRspLBit_42
    sizeof(word),  //traRspLBit_43
    sizeof(word),  //traRspLBit_44
    sizeof(word),  //traRspLBit_45
    sizeof(word),  //traRspLBit_46
    sizeof(word),  //traRspLBit_47
    sizeof(word),  //traRspLBit_48
    sizeof(word),  //traRspLBit_49
    sizeof(word),  //traRspLBit_50
    sizeof(word),  //traRspLBit_51
    sizeof(word),  //traRspLBit_52
    sizeof(word),  //traRspLBit_53
    sizeof(word),  //traRspLBit_54
    sizeof(word),  //traRspLBit_55
    sizeof(word),  //traRspLBit_56
    sizeof(word),  //traRspLBit_57
    sizeof(word),  //traRspLBit_58
    sizeof(word),  //traRspLBit_59
    sizeof(word),  //traRspLBit_60
    sizeof(word),  //traRspLBit_61
    sizeof(word),  //traRspLBit_62
    sizeof(word),  //traRspLBit_63
    sizeof(word),  //traRspLBit_64
    ///sizeof(word),  //traRspLBit_103
    sizeof(byte),  //traNeedDownloadLTWK
    13,  //traNomorTelepon
    sizeof(byte),  //traSumberRek
    999,  //traResponseInq
    54,  //traDataKartu
    2,  //traPreMonth
    2,  //traPreYear
    2,  //traCurMonth
    2,  //traCurYear
    16,  //traNomorKartu
    16,  //traNomorKartuPrint
    10,  //traUangPrint
    10,  //traSisaSaldoPrint
    8,  //traHashPrint
    8,  //traHash
    lenPinBlk,  //traHashContext
};
static word traMap[DIM(traBeg,traEnd)];
static char traFmt[DIM(traBeg,traEnd)]= {
    'A',  //traDatTim
    'N',  //traMnuItm
    'A',  //traCtx
    'A',  //traTrk2
    'A',  //traPan
    'A',  //traExpDat
    'A',  //traAmt
    'A',  //traTransType
    'A',  //traCardType
    'A',  //traTipAmt
    'A',  //traTotAmt
    'A',  //traDspAmt
    'A',  //traAutCod
    'A',  //traRspCod
    'A',  //traRrn
    'N',  //traTxnType
    'A',  //traIssName
    'A',  //traTrk21
    'A',  //traTrk22
    'N',  //traCrdSeq
    'N',  //traBinIdx
    'N',  //traAcqIdx
    'N',  //traIssIdx
    'A',  //traSrv
    'A',  //traTCPIPprm
    'A',  //traPriSec
    'A',  //traIPConfig
    'B',  //traPinBlk
    'N',  //traPinReq
    'N',  //traSgnReq
    'A',  //traTrk1
    'N',  //traMnuItmBeforeOffline
    'N',  //traTxnTypeBeforeOffline
    'N',  //traIdx
    'N',  //traLogTotalCount
    'A',  //traTypeName
    'A',  //traTypeCurName
    'A',  //traLogTxnTtlCnt
    'A',  //traLogTotalAmount
    'A',  //traAcqName
    'A',  //traFindRoc
    'N',  //traVoidFlag
    'A',  //traFmtAmt
    'A',  //traFmtTip
    'N',  //traVoidFlagContext
    'N',  //traMnuItmContext
    'A',  //traDatTimContext
    'N',  //traBinIdxContext
    'N',  //traAcqIdxContext
    'N',  //traIssIdxContext
    'A',  //traPanContext
    'A',  //traExpDatContext
    'A',  //traTrk2Context
    'A',  //traAutCodContext
    'A',  //traAmtContext
    'A',  //traTipAmtContext
    'A',  //traRrnContext
    'N',  //traEntModContext
    'N',  //traConCodeContext
    'A',  //traCardTypeContext
    'N',  //traEmvFullFlagContext
    'N',  //traTxnTypeContext
    'N',  //traTxnIdContext
    'N',  //traLocTypeContext
    'A',  //traTransTypeContext
    'N',  //traTmsMsg
    'N',  //traTmsMreRec
    'A',  //traTmsEmvFleNme
    'B',  //traTmsEmvFleHdl
    'N',  //traTmsEmvFleOff
    'N',  //traTmsEmvFleSze
    'N',  //traTmsEmvFlechnlen
    'N',  //traTmsDnlWidEmv
    'A',  //traPriIpBuf
    'A',  //traPriPortBuf
    'A',  //traSecIpBuf
    'A',  //traSecPortBuf
    'A',  //traFmtDate
    'A',  //traFmtTime
    'N',  //traInvNum
    'A',  //traRspDspLin1
    'A',  //traRspDspLin2
    'A',  //traAppPrfNam
    'B',  //emvAppPrfNam
    'B',  //emvAppLbl
    'B',  //emvTrnSeqCnt
    'B',  //emvTrk2
    'B',  //emvExpDat
    'B',  //emvCVM
    'B',  //emvCrdAvn
    'B',  //emvChdNam
    'B',  //emvLanPrf
    'B',  //emvRSAKeyExp
    'B',  //emvRSAKey
    'B',  //emvCVMOutRes
    'B',  //emvFrcOnl
    'B',  //emvHotLst
    'B',  //emvCID
    'B',  //emvTrmDc1
    'B',  //emvTrmDc2
    'B',  //emvOnlSta
    'B',  //emvAuthRes
    'B',  //emvCommOk
    'B',  //emvIssAutDta
    'B',  //emvAutCod
    'B',  //emvIssSc1
    'B',  //emvIssSc2
    'A',  //traEMSale
    'A',  //traChipSwipe
    'N',  //traTxnId
    'A',  //traBlockPan
    'N',  //traTipFlag
    'N',  //traFallback
    'A',  //traSrvCod
    'N',  //traEmvTrnType
    'A',  //traExpDatFmt
    'N',  //traCustFlag
    'A',  //traAutCodOff
    'A',  //traEmvICC
    'N',  //traInputPin
    'N',  //traNeedLogon
    'A',  //traRspBit13
    'A',  //traRspBit12
    'A',  //traMti
    'A',  //traPanSeq
    'N',  //traEmvFullFlag
    'N',  //traLoginFlag
    'N',  //traIsSign
    'A',  //traWorkingKey
    'A',  //traSerNum
    'A',  //traLeMsg
    'A',  //traMAC
    'N',  //traMsgFlag
    'N',  //traBit23On
    'A',  //traLTWKDEK
    'N',  //traMnuItmVoid
    'A',  //traTimeSend
    'A',  //traAppName
    'A',  //traInvTransType
    'A',  //traLine3
    'N',  //traBinReq
    'A',  //traPinInput
    'A',  //traBit48PwrBuy
    'A',  //traAmtMonthly
    'A',  //traMonth
    'N',  //traEmvReqFlag
    'N',  //traMnuItmTenor
    'A',  //traPwrBuyType
    'N',  //traReader
    'A',  //traSAMPreStatus
    'A',  //traSAMTransactionReport
    'A',  //traAmtTopUp
    'A',  //traAmtPrepaid
    'A',  //traTrk2Prepaid
    'A',  //traInquBit48Prepaid
    'A',  //traBit58
    'A',  //traSAMHost
    'A',  //traTrkPrepaidPrint
    'A',  //traTrkPrepaidTapPrint
    'A',  //traTrkPrepaidSwipePrint
    'A',  //traServerAuthPrepaid
    'A',  //traHastPrepaid
    'A',  //traTidTxr
    'A',  //traTidIns
    'A',  //traCardNo
    'A',  //traPayment
    'A',  //traBalance
    'A',  //traInsId
    'A',  //traSaldoAKhir
    'A',  //traSaldoAwal
    'A',  //traTCCode
    'A',  //traAppCode
    'A',  //tramerchantAmt
    'A',  //traIssuerAmt
    'A',  //traPoolingAmt
    'A',  //traSaleAmT
    'A',  //traPrepaidTotal
    'A',  //traRevBit48Prepaid
    'A',  //traRevBit58Prepaid
    'N',  //traLogTotalCounTopup
    'A',  //traLogTotalAmountTopup
    'N',  //traStateFlag
    'N',  //traLogTotalCounTelkom
    'A',  //traLogTotalAmountTelkom
    'N',  //traLogTotalCounSatelindo
    'A',  //traLogTotalAmountSatelindo
    'N',  //traLogTotalCounTelkomsel
    'A',  //traLogTotalAmountTelkomsel
    'N',  //traLogTotalCounExcelcom
    'A',  //traLogTotalAmountExcelcom
    'N',  //traLogTotalCounEsia
    'A',  //traLogTotalAmountEsia
    'N',  //traLogTotalCounPLN
    'A',  //traLogTotalAmountPLN
    'N',  //traLogTotalCounFirstMedia
    'A',  //traLogTotalAmountFirstMedia
    'N',  //traLogTotalCounIndovision
    'A',  //traLogTotalAmountIndovision
    'N',  //traLogTotalCounOtoMulti
    'A',  //traLogTotalAmountOtoMulti
    'N',  //traLogTotalCounMAtm
    'A',  //traLogTotalAmountMAtm
    'A',  //traLogTotalAmountMINIAtm
    'A',  //traRspBit58ServerAuth
    'N',  //traLogTotalCounComm
    'A',  //traAccDest
    'A',  //traCode
    'A',  //traSourceBuyRate
    'A',  //traSourceSaleRate
    'A',  //traDestBuyRate
    'A',  //traDestSaleRate
    'A',  //traCodeDest
    'A',  //traTunai
    'A',  //traAmtIDR
    'N',  //traLogTotalCounTunai
    'A',  //traLogTotalAmountTunai
    'N',  //traLogTotalCounTransfer
    'A',  //traLogTotalAmountTransfer
    'N',  //traLogTotalCounCC
    'A',  //traLogTotalAmountCC
    'A',  //traLogTotalAmountTransferUSD
    'N',  //traLogTotalCounTransferUSD
    'A',  //traLogTotalAmountTransferSGD
    'N',  //traLogTotalCounTransferSGD
    'A',  //traLogTotalAmountTransferJPN
    'N',  //traLogTotalCounTransferJPN
    'N',  //traPWCVoidFlag
    'A',  //traCardTypeTBM
    'N',  //traAlreadyConnect
    'A',  //traCurBat
    'B',  //traEmvAid
    'B',  //traPrcCod
    'A',  //traTimeRecv
    'N',  //traTcFlag
    'A',  //traTrack1
    'A',  //traTrack2
    'A',  //traTrack3
    'A',  //traCurValas
    'N',  //traOnUsOffUs
    'N',  //traFlagDBMCVS
    'N',  //traSTAN
    'A',  //traRspMti
    'A',  //traRspBitmap
    'A',  //traRspTID
    'A',  //traRspMID
    'A',  //traRspSTAN
    'A',  //traRspRRN
    'A',  //traRspAutCod
    'A',  //traRspAmount
    'A',  //traRspTrack2
    'A',  //traReqSTAN
    'A',  //traReqTID
    'A',  //traReqMID
    'A',  //traCalcRspMAC
    'A',  //traRspMAC
    'A',  //traReqAmount
    'A',  //traRspBitBeg
    'A',  //traRspBit_1
    'A',  //traRspBit_2
    'A',  //traRspBit_3
    'A',  //traRspBit_4
    'A',  //traRspBit_5
    'A',  //traRspBit_6
    'A',  //traRspBit_7
    'A',  //traRspBit_8
    'A',  //traRspBit_9
    'A',  //traRspBit_10
    'A',  //traRspBit_11
    'A',  //traRspBit_12
    'A',  //traRspBit_13
    'A',  //traRspBit_14
    'A',  //traRspBit_15
    'A',  //traRspBit_16
    'A',  //traRspBit_17
    'A',  //traRspBit_18
    'A',  //traRspBit_19
    'A',  //traRspBit_20
    'A',  //traRspBit_21
    'A',  //traRspBit_22
    'A',  //traRspBit_23
    'A',  //traRspBit_24
    'A',  //traRspBit_25
    'A',  //traRspBit_26
    'A',  //traRspBit_27
    'A',  //traRspBit_28
    'A',  //traRspBit_29
    'A',  //traRspBit_30
    'A',  //traRspBit_31
    'A',  //traRspBit_32
    'A',  //traRspBit_33
    'A',  //traRspBit_34
    'A',  //traRspBit_35
    'A',  //traRspBit_36
    'A',  //traRspBit_37
    'A',  //traRspBit_38
    'A',  //traRspBit_39
    'A',  //traRspBit_40
    'A',  //traRspBit_41
    'A',  //traRspBit_42
    'A',  //traRspBit_43
    'A',  //traRspBit_44
    'A',  //traRspBit_45
    'A',  //traRspBit_46
    'A',  //traRspBit_47
    'A',  //traRspBit_48
    'A',  //traRspBit_49
    'A',  //traRspBit_50
    'A',  //traRspBit_51
    'A',  //traRspBit_52
    'A',  //traRspBit_53
    'A',  //traRspBit_54
    'A',  //traRspBit_55
    'A',  //traRspBit_56
    'A',  //traRspBit_57
    'A',  //traRspBit_58
    'A',  //traRspBit_59
    'A',  //traRspBit_60
    'A',  //traRspBit_61
    'A',  //traRspBit_62
    'A',  //traRspBit_63
    'A',  //traRspBit_64
    ///'A',  //traRspBit_103
    'N',  //traRspLBitBeg
    'N',  //traRspLBit_1
    'N',  //traRspLBit_2
    'N',  //traRspLBit_3
    'N',  //traRspLBit_4
    'N',  //traRspLBit_5
    'N',  //traRspLBit_6
    'N',  //traRspLBit_7
    'N',  //traRspLBit_8
    'N',  //traRspLBit_9
    'N',  //traRspLBit_10
    'N',  //traRspLBit_11
    'N',  //traRspLBit_12
    'N',  //traRspLBit_13
    'N',  //traRspLBit_14
    'N',  //traRspLBit_15
    'N',  //traRspLBit_16
    'N',  //traRspLBit_17
    'N',  //traRspLBit_18
    'N',  //traRspLBit_19
    'N',  //traRspLBit_20
    'N',  //traRspLBit_21
    'N',  //traRspLBit_22
    'N',  //traRspLBit_23
    'N',  //traRspLBit_24
    'N',  //traRspLBit_25
    'N',  //traRspLBit_26
    'N',  //traRspLBit_27
    'N',  //traRspLBit_28
    'N',  //traRspLBit_29
    'N',  //traRspLBit_30
    'N',  //traRspLBit_31
    'N',  //traRspLBit_32
    'N',  //traRspLBit_33
    'N',  //traRspLBit_34
    'N',  //traRspLBit_35
    'N',  //traRspLBit_36
    'N',  //traRspLBit_37
    'N',  //traRspLBit_38
    'N',  //traRspLBit_39
    'N',  //traRspLBit_40
    'N',  //traRspLBit_41
    'N',  //traRspLBit_42
    'N',  //traRspLBit_43
    'N',  //traRspLBit_44
    'N',  //traRspLBit_45
    'N',  //traRspLBit_46
    'N',  //traRspLBit_47
    'N',  //traRspLBit_48
    'N',  //traRspLBit_49
    'N',  //traRspLBit_50
    'N',  //traRspLBit_51
    'N',  //traRspLBit_52
    'N',  //traRspLBit_53
    'N',  //traRspLBit_54
    'N',  //traRspLBit_55
    'N',  //traRspLBit_56
    'N',  //traRspLBit_57
    'N',  //traRspLBit_58
    'N',  //traRspLBit_59
    'N',  //traRspLBit_60
    'N',  //traRspLBit_61
    'N',  //traRspLBit_62
    'N',  //traRspLBit_63
    'N',  //traRspLBit_64
    ///'N',  //traRspLBit_103
    'N',  //traNeedDownloadLTWK
    'A',  //traNomorTelepon
    'N',  //traSumberRek
    'A',  //traResponseInq
    'A',  //traDataKartu
    'A',  //traPreMonth
    'A',  //traPreYear
    'A',  //traCurMonth
    'A',  //traCurYear
    'A',  //traNomorKartu
    'A',  //traNomorKartuPrint
    'A',  //traUangPrint
    'A',  //traSisaSaldoPrint
    'A',  //traHashPrint
    'A',  //traHash
    'A',  //traHashContext
};

typedef struct sVol{
    char _traDatTim[lenDatTim];
    word _traMnuItm;
    char _traCtx[dspW];
    char _traTrk2[lenTrk2];
    char _traPan[lenPan];
    char _traExpDat[lenExpDat];
    char _traAmt[lenAmt];
    char _traTransType[lenCardTransType];
    char _traCardType[lenCardTransType];
    char _traTipAmt[lenAmt];
    char _traTotAmt[20];
    char _traDspAmt[20];
    char _traAutCod[lenAutCod];
    char _traRspCod[lenRspCod];
    char _traRrn[lenRrn];
    byte _traTxnType;
    char _traIssName[dspW];
    char _traTrk21[dspW];
    char _traTrk22[dspW];
    byte _traCrdSeq;
    byte _traBinIdx;
    byte _traAcqIdx;
    byte _traIssIdx;
    char _traSrv[lenSrv];
    char _traTCPIPprm[dspW];
    char _traPriSec[dspW];
    char _traIPConfig[dspW];
    byte _traPinBlk[1+lenPinBlk];
    byte _traPinReq;
    byte _traSgnReq;
    char _traTrk1[lenTrk2];
    word _traMnuItmBeforeOffline;
    byte _traTxnTypeBeforeOffline;
    word _traIdx;
    word _traLogTotalCount;
    char _traTypeName[lenName];
    char _traTypeCurName[4];
    char _traLogTxnTtlCnt[3];
    char _traLogTotalAmount[lenAmt];
    char _traAcqName[lenName];
    char _traFindRoc[lenInvNum];
    byte _traVoidFlag;
    char _traFmtAmt[20];
    char _traFmtTip[lenAmt];
    byte _traVoidFlagContext;
    word _traMnuItmContext;
    char _traDatTimContext[lenDatTim];
    byte _traBinIdxContext;
    byte _traAcqIdxContext;
    byte _traIssIdxContext;
    char _traPanContext[lenPan];
    char _traExpDatContext[lenExpDat];
    char _traTrk2Context[lenTrk2];
    char _traAutCodContext[lenAutCod];
    char _traAmtContext[lenAmt];
    char _traTipAmtContext[lenAmt];
    char _traRrnContext[lenRrn];
    char _traEntModContext;
    byte _traConCodeContext;
    char _traCardTypeContext[lenCardTransType];
    byte _traEmvFullFlagContext;
    byte _traTxnTypeContext;
    byte _traTxnIdContext;
    byte _traLocTypeContext;
    char _traTransTypeContext[lenCardTransType];
    byte _traTmsMsg;
    byte _traTmsMreRec;
    char _traTmsEmvFleNme[lenFleNme];
    byte _traTmsEmvFleHdl[1+lenFleHdl];
    card _traTmsEmvFleOff;
    card _traTmsEmvFleSze;
    word _traTmsEmvFlechnlen;
    byte _traTmsDnlWidEmv;
    char _traPriIpBuf[lenSrv];
    char _traPriPortBuf[lenSrv];
    char _traSecIpBuf[lenSrv];
    char _traSecPortBuf[lenSrv];
    char _traFmtDate[lenDatTim];
    char _traFmtTime[lenDatTim];
    card _traInvNum;
    char _traRspDspLin1[dspW];
    char _traRspDspLin2[dspW];
    char _traAppPrfNam[lenAppPrfNam];
    byte _emvAppPrfNam[1+lenAppPrfNam];
    byte _emvAppLbl[1+lenAppPrfNam];
    byte _emvTrnSeqCnt[1+lenTrnSeqCnt];
    byte _emvTrk2[1+lenEmvTrk2];
    byte _emvExpDat[1+lenEmvExpDat];
    byte _emvCVM[1+lenCVM];
    byte _emvCrdAvn[1+lenCrdAvn];
    byte _emvChdNam[1+lenChdNam];
    byte _emvLanPrf[1+lenLanPrf];
    byte _emvRSAKeyExp[1+lenRSAKeyExp];
    byte _emvRSAKey[1+lenRSAKey];
    byte _emvCVMOutRes[1+lenCVMOutRes];
    byte _emvFrcOnl[1+lenFrcOnl];
    byte _emvHotLst[1+lenHotLst];
    byte _emvCID[1+lenCID];
    byte _emvTrmDc1[1+lenTrmDcs];
    byte _emvTrmDc2[1+lenTrmDcs];
    byte _emvOnlSta[1+lenOnlSta];
    byte _emvAuthRes[1+lenAuthRes];
    byte _emvCommOk[1+lenCommOk];
    byte _emvIssAutDta[1+lenIssAutDta];
    byte _emvAutCod[1+lenAutCod];
    byte _emvIssSc1[1+lenIssSc1];
    byte _emvIssSc2[1+lenIssSc2];
    char _traEMSale[7];
    char _traChipSwipe[10];
    byte _traTxnId;
    char _traBlockPan[lenPan];
    byte _traTipFlag;
    byte _traFallback;
    char _traSrvCod[3];
    byte _traEmvTrnType;
    char _traExpDatFmt[5];
    byte _traCustFlag;
    char _traAutCodOff[lenAutCod];
    char _traEmvICC[lenEmvICC];
    byte _traInputPin;
    byte _traNeedLogon;
    char _traRspBit13[2];
    char _traRspBit12[3];
    char _traMti[lenMti];
    char _traPanSeq[2];
    byte _traEmvFullFlag;
    byte _traLoginFlag;
    byte _traIsSign;
    char _traWorkingKey[32];
    char _traSerNum[lenTid];
    char _traLeMsg[37];
    char _traMAC[8];
    byte _traMsgFlag;
    byte _traBit23On;
    char _traLTWKDEK[16];
    word _traMnuItmVoid;
    char _traTimeSend[6];
    char _traAppName[13];
    char _traInvTransType[22];
    char _traLine3[20];
    byte _traBinReq;
    char _traPinInput[6];
    char _traBit48PwrBuy[128];
    char _traAmtMonthly[20];
    char _traMonth[9];
    byte _traEmvReqFlag;
    word _traMnuItmTenor;
    char _traPwrBuyType[16];
    byte _traReader;
    char _traSAMPreStatus[1];
    char _traSAMTransactionReport[47];
    char _traAmtTopUp[12];
    char _traAmtPrepaid[12];
    char _traTrk2Prepaid[37];
    char _traInquBit48Prepaid[256];
    char _traBit58[128];
    char _traSAMHost[256];
    char _traTrkPrepaidPrint[16];
    char _traTrkPrepaidTapPrint[20];
    char _traTrkPrepaidSwipePrint[25];
    char _traServerAuthPrepaid[256];
    char _traHastPrepaid[16];
    char _traTidTxr[24];
    char _traTidIns[16];
    char _traCardNo[32];
    char _traPayment[20];
    char _traBalance[20];
    char _traInsId[2];
    char _traSaldoAKhir[20];
    char _traSaldoAwal[20];
    char _traTCCode[26];
    char _traAppCode[6];
    char _tramerchantAmt[15];
    char _traIssuerAmt[15];
    char _traPoolingAmt[15];
    char _traSaleAmT[15];
    char _traPrepaidTotal[15];
    char _traRevBit48Prepaid[256];
    char _traRevBit58Prepaid[256];
    word _traLogTotalCounTopup;
    char _traLogTotalAmountTopup[lenAmt];
    byte _traStateFlag;
    word _traLogTotalCounTelkom;
    char _traLogTotalAmountTelkom[lenAmt];
    word _traLogTotalCounSatelindo;
    char _traLogTotalAmountSatelindo[lenAmt];
    word _traLogTotalCounTelkomsel;
    char _traLogTotalAmountTelkomsel[lenAmt];
    word _traLogTotalCounExcelcom;
    char _traLogTotalAmountExcelcom[lenAmt];
    word _traLogTotalCounEsia;
    char _traLogTotalAmountEsia[lenAmt];
    word _traLogTotalCounPLN;
    char _traLogTotalAmountPLN[lenAmt];
    word _traLogTotalCounFirstMedia;
    char _traLogTotalAmountFirstMedia[lenAmt];
    word _traLogTotalCounIndovision;
    char _traLogTotalAmountIndovision[lenAmt];
    word _traLogTotalCounOtoMulti;
    char _traLogTotalAmountOtoMulti[lenAmt];
    word _traLogTotalCounMAtm;
    char _traLogTotalAmountMAtm[lenAmt];
    char _traLogTotalAmountMINIAtm[lenAmt];
    char _traRspBit58ServerAuth[128];
    word _traLogTotalCounComm;
    char _traAccDest[19];
    char _traCode[3];
    char _traSourceBuyRate[13];
    char _traSourceSaleRate[13];
    char _traDestBuyRate[13];
    char _traDestSaleRate[13];
    char _traCodeDest[3];
    char _traTunai[16];
    char _traAmtIDR[lenAmt];
    word _traLogTotalCounTunai;
    char _traLogTotalAmountTunai[lenAmt];
    word _traLogTotalCounTransfer;
    char _traLogTotalAmountTransfer[lenAmt];
    word _traLogTotalCounCC;
    char _traLogTotalAmountCC[lenAmt];
    char _traLogTotalAmountTransferUSD[24];
    word _traLogTotalCounTransferUSD;
    char _traLogTotalAmountTransferSGD[24];
    word _traLogTotalCounTransferSGD;
    char _traLogTotalAmountTransferJPN[24];
    word _traLogTotalCounTransferJPN;
    byte _traPWCVoidFlag;
    char _traCardTypeTBM[lenCardTransType ];
    byte _traAlreadyConnect;
    char _traCurBat[lenInvNum];
    byte _traEmvAid[1+lenAID];
    byte _traPrcCod[1+lenPrcCod];
    char _traTimeRecv[6];
    byte _traTcFlag;
    char _traTrack1[lenTrack];
    char _traTrack2[lenTrack];
    char _traTrack3[lenTrack];
    char _traCurValas[3];
    byte _traOnUsOffUs;
    byte _traFlagDBMCVS;
    card _traSTAN;
    char _traRspMti[lenMti];
    char _traRspBitmap[lenBitmap];
    char _traRspTID[lenTid];
    char _traRspMID[lenMid];
    char _traRspSTAN[lenSTAN];
    char _traRspRRN[lenRrn];
    char _traRspAutCod[lenAutCod];
    char _traRspAmount[lenAmt];
    char _traRspTrack2[lenTrk2];
    char _traReqSTAN[lenSTAN];
    char _traReqTID[lenTid];
    char _traReqMID[lenMid];
    char _traCalcRspMAC[8];
    char _traRspMAC[8];
    char _traReqAmount[lenAmt];
    char _traRspBitBeg[lenBit1];
    char _traRspBit_1[lenBit1];
    char _traRspBit_2[lenBit2];
    char _traRspBit_3[lenBit3];
    char _traRspBit_4[lenBit4];
    char _traRspBit_5[lenBit5];
    char _traRspBit_6[lenBit6];
    char _traRspBit_7[lenBit7];
    char _traRspBit_8[lenBit8];
    char _traRspBit_9[lenBit9];
    char _traRspBit_10[lenBit10];
    char _traRspBit_11[lenBit11];
    char _traRspBit_12[lenBit12];
    char _traRspBit_13[lenBit13];
    char _traRspBit_14[lenBit14];
    char _traRspBit_15[lenBit15];
    char _traRspBit_16[lenBit16];
    char _traRspBit_17[lenBit17];
    char _traRspBit_18[lenBit18];
    char _traRspBit_19[lenBit19];
    char _traRspBit_20[lenBit20];
    char _traRspBit_21[lenBit21];
    char _traRspBit_22[lenBit22];
    char _traRspBit_23[lenBit23];
    char _traRspBit_24[lenBit24];
    char _traRspBit_25[lenBit25];
    char _traRspBit_26[lenBit26];
    char _traRspBit_27[lenBit27];
    char _traRspBit_28[lenBit28];
    char _traRspBit_29[lenBit29];
    char _traRspBit_30[lenBit30];
    char _traRspBit_31[lenBit31];
    char _traRspBit_32[lenBit32];
    char _traRspBit_33[lenBit33];
    char _traRspBit_34[lenBit34];
    char _traRspBit_35[lenBit35];
    char _traRspBit_36[lenBit36];
    char _traRspBit_37[lenBit37];
    char _traRspBit_38[lenBit38];
    char _traRspBit_39[lenBit39];
    char _traRspBit_40[lenBit40];
    char _traRspBit_41[lenBit41];
    char _traRspBit_42[lenBit42];
    char _traRspBit_43[lenBit43];
    char _traRspBit_44[lenBit44];
    char _traRspBit_45[lenBit45];
    char _traRspBit_46[lenBit46];
    char _traRspBit_47[lenBit47];
    char _traRspBit_48[lenBit48];
    char _traRspBit_49[lenBit49];
    char _traRspBit_50[lenBit50];
    char _traRspBit_51[lenBit51];
    char _traRspBit_52[lenBit52];
    char _traRspBit_53[lenBit53];
    char _traRspBit_54[lenBit54];
    char _traRspBit_55[lenBit55];
    char _traRspBit_56[lenBit56];
    char _traRspBit_57[lenBit57];
    char _traRspBit_58[lenBit58];
    char _traRspBit_59[lenBit59];
    char _traRspBit_60[lenBit60];
    char _traRspBit_61[lenBit61];
    char _traRspBit_62[lenBit62];
    char _traRspBit_63[lenBit63];
    char _traRspBit_64[lenBit64];
/////	char _traRspBit_103[lenBit103];
    word _traRspLBitBeg;
    word _traRspLBit_1;
    word _traRspLBit_2;
    word _traRspLBit_3;
    word _traRspLBit_4;
    word _traRspLBit_5;
    word _traRspLBit_6;
    word _traRspLBit_7;
    word _traRspLBit_8;
    word _traRspLBit_9;
    word _traRspLBit_10;
    word _traRspLBit_11;
    word _traRspLBit_12;
    word _traRspLBit_13;
    word _traRspLBit_14;
    word _traRspLBit_15;
    word _traRspLBit_16;
    word _traRspLBit_17;
    word _traRspLBit_18;
    word _traRspLBit_19;
    word _traRspLBit_20;
    word _traRspLBit_21;
    word _traRspLBit_22;
    word _traRspLBit_23;
    word _traRspLBit_24;
    word _traRspLBit_25;
    word _traRspLBit_26;
    word _traRspLBit_27;
    word _traRspLBit_28;
    word _traRspLBit_29;
    word _traRspLBit_30;
    word _traRspLBit_31;
    word _traRspLBit_32;
    word _traRspLBit_33;
    word _traRspLBit_34;
    word _traRspLBit_35;
    word _traRspLBit_36;
    word _traRspLBit_37;
    word _traRspLBit_38;
    word _traRspLBit_39;
    word _traRspLBit_40;
    word _traRspLBit_41;
    word _traRspLBit_42;
    word _traRspLBit_43;
    word _traRspLBit_44;
    word _traRspLBit_45;
    word _traRspLBit_46;
    word _traRspLBit_47;
    word _traRspLBit_48;
    word _traRspLBit_49;
    word _traRspLBit_50;
    word _traRspLBit_51;
    word _traRspLBit_52;
    word _traRspLBit_53;
    word _traRspLBit_54;
    word _traRspLBit_55;
    word _traRspLBit_56;
    word _traRspLBit_57;
    word _traRspLBit_58;
    word _traRspLBit_59;
    word _traRspLBit_60;
    word _traRspLBit_61;
    word _traRspLBit_62;
    word _traRspLBit_63;
    word _traRspLBit_64;
	///word _traRspLBit_103;
    byte _traNeedDownloadLTWK;
    char _traNomorTelepon[13];
    byte _traSumberRek;
    char _traResponseInq[999];
    char _traDataKartu[54];
    char _traPreMonth[2];
    char _traPreYear[2];
    char _traCurMonth[2];
    char _traCurYear[2];
    char _traNomorKartu[16];
    char _traNomorKartuPrint[16];
    char _traUangPrint[10];
    char _traSisaSaldoPrint[10];
    char _traHashPrint[8];
    char _traHash[8];
    char _traHashContext[lenPinBlk];
}tVol;
static tVol vol; //reserve volatile memory


#define __MAP_H
#endif

